# -*- coding: utf-8 -*-
"""search_all_tweets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Lpc6yv_U9vaYD2VKYN1xBCUMHG4G4uv
"""


import tweepy
import pandas as pd
from datetime import datetime, timedelta
import time
import sys
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import pathlib
import os

savelink = "."
files = os.listdir(savelink)
print(files)

# fuction to extract data from tweet object
def extract_tweet_attributes_to_json_and_save(tweet_objects, savelink, curr_yr, curr_month, print_head=False):
    # create empty list
    tweet_list = []
    
    # loop through tweet objects
    for tweet in tweet_objects:
        tweet_id = tweet.id # unique integer identifier for tweet
        text = tweet.text # utf-8 text of tweet
        lang = tweet.lang
        # append attributes to list
        tweet_list.append({'tweet_id':tweet_id, 
                           'text':text, 
                           'lang':lang})
    

    # create dataframe   
    df = pd.DataFrame(tweet_list, columns=['tweet_id',
                                           'text', 
                                           'lang'])

    # Preview collected data
    if print_head:
        print(df[{'tweet_id', 'text', 'lang'}].head())

    # # Save to JSON
    # print(f'Saving {filename}...')
    # with open(filename, 'w') as f:
    #     f.write(df.to_json(orient='records', lines=True))
    # print(f'{filename} saved.')

    # save to gdrive
    with open(savelink + '/' + str(curr_yr) + '-' + str(curr_month) +'.json','w') as f:
      f.write(df.to_json(orient='records', lines=True))

client = tweepy.Client("REPLACE_WITH_YOUR_KEY")


STOP_WORDS = list(set(
"""
akin
aking
ako
alin
amin
aming
ang
ano
atin
ating
bababa
bago
bakit
bawat
dahil
dapat
din
dito
doon
gagawin
gusto
habang
hanggang
hindi
huwag
iba
ibaba
ibabaw
ibig
ikaw
ilagay
ilalim
ilan
inyong
isa
isang
itaas
ito
iyo
iyon
iyong
kahit
kami
kanila
kanilang
kanino
kanya
kanyang
kapag
kapwa
katulad
kaya
kaysa
kong
kulang
kumuha
kung
laban
lahat
lamang
likod
maging
mahusay
makita
marami
masyado
mga
minsan
mismo
mula
muli
naging
nais
nakita
namin
napaka
narito
nasaan
ngayon
nila
nilang
nito
niya
niyang
noon
paano
pababa
panahon
para
paraan
pareho
pataas
pero
saan
sabi
sabihin
sarili
sila
sino
siya
tayo
tungkol
walang
""".split()
))

# Fix for "Rules must contain at least one positive, non-stopword clause (at position 1)", append a non stopword at position 1 of query.
STOP_WORDS = " OR ".join(STOP_WORDS)

import time
from datetime import datetime, timezone

start_yr = 2022
end_yr = 2022

curr_yr = start_yr
while curr_yr <= end_yr:
  curr_month = 1 # reset
  while curr_month <= 12:
    start_time = datetime(curr_yr, curr_month, 1).astimezone()
    print(start_time)
    start_time = start_time.isoformat()
    print(start_time)

    end_time = datetime(curr_yr, curr_month, 28).astimezone()
    print(end_time)
    end_time = end_time.isoformat()
    print(end_time)

    # PARAMETERS
    max_sleeps = 1000000
    n_sleep = 0
    tweet_ctr = 0
    tweets = [] # initialize empty list
    prev_count = 0
    sleep_time_seconds = 3
    sleep_time_minutes = sleep_time_seconds / 60
    max_tweets_per_month = 1000000
    max_results = 500
    save_interval = 50
    n_requested = 0

    tweet_list = []
    try:
        print(start_time)
        print(end_time)
        tweets = client.search_all_tweets(f"({STOP_WORDS}) lang:tl -is:retweet", start_time=start_time, end_time=end_time, next_token=None, max_results = max_results, tweet_fields=["lang"])
        tweet_list += tweets.data
    except Exception as e:
        print(e)

        tweet_ctr = len(tweet_list)

        if n_sleep == max_sleeps: # if reached max num of sleeps without progress
            break

        if n_sleep == 0: # first time sleeping
            prev_count = tweet_ctr # remember tweet count

        if prev_count == tweet_ctr: # if no progress, increment sleep
            n_sleep += 1
        else:                       # reset if there's progress
            prev_count = tweet_ctr  # update prev_size
            n_sleep = 0

        # Print message
        print(f"Sleeping for {sleep_time_minutes} minutes ({n_sleep} out of {max_sleeps})...")
        # Get current time
        t = time.localtime()
        current_time = time.strftime("%H:%M:%S", t)
        # Print start time
        print(f"Sleep start: {current_time}")
        # Sleep
        time.sleep(sleep_time_seconds)
        continue


    # can go up to 300 requests
    while(tweets.meta['next_token'] != None):
        if len(tweet_list) >= max_tweets_per_month:
            break

        if n_requested % save_interval == 0: # save file for every save_interval e.g. save for every 50 requests
            print(f"saving checkpoint {savelink + '/' + str(curr_yr) + '-' + str(curr_month)}...")
            print(f"tweet count: {len(tweet_list)}")
            extract_tweet_attributes_to_json_and_save(tweet_list, savelink, curr_yr, curr_month) # save to json
        
        try:
            tweets = client.search_all_tweets(f"({STOP_WORDS}) lang:tl -is:retweet", start_time=start_time, end_time=end_time, next_token=tweets.meta['next_token'], max_results = max_results, tweet_fields=["lang"])
            tweet_list += tweets.data
            print(len(tweet_list))
        except Exception as e:
            print(e)

            tweet_ctr = len(tweet_list)

            if n_sleep == max_sleeps: # if reached max num of sleeps without progress
                break

            if n_sleep == 0: # first time sleeping
                prev_count = tweet_ctr # remember tweet count

            if prev_count == tweet_ctr: # if no progress, increment sleep
                n_sleep += 1
            else:                       # reset if there's progress
                prev_count = tweet_ctr  # update prev_size
                n_sleep = 0

            # Print message
            print(f"Sleeping for {sleep_time_minutes} minutes ({n_sleep} out of {max_sleeps})...")
            # Get current time
            t = time.localtime()
            current_time = time.strftime("%H:%M:%S", t)
            # Print start time
            print(f"Sleep start: {current_time}")
            # Sleep
            time.sleep(sleep_time_seconds)
            continue

        n_requested += 1

    # Save tweets to json file
    if len(tweet_list) > 0: # if tweets list is not empty
        extract_tweet_attributes_to_json_and_save(tweet_list, savelink, curr_yr, curr_month) # save to json

    curr_month += 1

  curr_yr += 1

